alias st="source $HOME/.alias/st.sh"
alias cm="source $HOME/.alias/cm.sh"
alias red="export ContainerName=\"red\" && source $HOME/.alias/docker-runenv.sh"
alias blue="export ContainerName=\"blue\" && source $HOME/.alias/docker-runenv.sh"
alias yellow="export ContainerName=\"yellow\" && source $HOME/.alias/docker-runenv.sh"
alias horizon="export ContainerName=\"horizon\" && source $HOME/.alias/docker-runenv.sh"